version: '3'

services:
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    volumes:
      - './dist:/dist'
    networks:
      - app

  back-end:
    container_name: back-end
    build:
      context: .
      dockerfile: ./back-end/Dockerfile
    env_file:
      - back-end/.env
    volumes:
      - './dist:/dist'
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - app

networks:
    app:
      driver: bridge
