version: '3'

services:
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    volumes:
      - './dist:/dist'
    command: 'npm run webpack:prod'
    networks:
      - app

networks:
    app:
      driver: bridge
